data-govt-nz/ckanext-security

- ckanext/security/validators.py
Root reason:
`ckanext.security.validators.user_password_validator` raise a `ValueError`
instead of a `ckan.logic.ValidationError`, ckan can not handle it in
`core.ckan.controllers.user._save_edit`
Solution:
Raise `ValidationError` with correct args then it can be handled.
External: WR277492
> Fix invalid new password validation error

- ckanext/security/validators.py
Raise Invalid instead of ValidationError is a better way for form,
according to other validators.
External: WR277308
> Raise Invalid exception in user_password_validator

- ckanext/security/middleware.py
The [suggested commit](data-govt-nz/ckan@74f7886#diff-b210bb60891168d37e3cacbb134aa6f3R132) to add CSRF middleware silently fails. This should be addressed separately.
The import fails because [ckanext.security.middleware](https://github.com/data-govt-nz/ckanext-security/blob/master/ckanext/security/middleware.py#L7) imports from the wrong path `ckanext.security.memcached`, which should be `ckanext.security.cache.clients`.
> Fix memcached client import path

- README.md
I've spent the last few hours trying to get a CKAN instance running and *finally* fixed it by applying the patch.
Hopefully adding this will save someone else many hours of debugging.
> Add information to describe possible error

- ckanext/security/plugin.py
- setup.py
Remove "catalyst" from this plugin, as the intention is to merge all of
the changes from this plugin in to ckan itself.
This PR fixes issue #1 .
> Make plugin name not vendor specific

- ckanext/security/middleware.py
Previously every static file request, for example js,css,woff files
would regenerate and update the CSRF token set in the cookie. This meant
that if a user submitted a form before the page was finished loading, their
CSRF token would be older than the one on the server and so the request
would fail.
> fix static file requests regenerating CSRF token

- ckanext/security/middleware.py
The app would serve 500's when an api Post request is made.
1. whitelist any request which starts with the path `/api`
2. fix a 500 error caused by calling `self.referer.startswith` when referer is `None`.
> fix issue where api post requests would 500 error

- README.md
- ckanext/security/authenticator.py
- ckanext/security/cache/clients.py
- ckanext/security/cache/login.py
- ckanext/security/middleware.py
- setup.py
Includes changes to support moving from memcache to redis, and support for ckan 2.7.
Original PR for redis support: https://github.com/data-govt-nz/ckanext-security/pull/16
> support ckan 2.7 and redis

- ckanext/security/middleware.py
A well formed http request should have a `Content-type` header, but when
the content-type is not defined, it will cause our security middleware
to throw a keyerror.
This change makes sure that an error is not thrown in this case. When
there is no content-type header, the token will not be refreshed
> Handle http request without content-type

- README.md
- ckanext/security/plugin.py
- ckanext/security/resource_upload_validator.py
- setup.py
This feature tightens up the types of allowed files for resource uploads by excluding .exe files.
It provides user feedback if the uploaded file is blacklisted.
See README changes for more information.
> Prevent resource uploads for certain file types

- ckanext/security/controllers.py
- ckanext/security/templates/security/configure_mfa.html
Also prevents autocomplete on the 2fa input, otherwise browsers display a list of previous 2fa codes, not helpful.
> Use flash message pattern for 2fa feedback

- ckanext/security/controllers.py
- ckanext/security/fanstatic/login_ajax.js
- ckanext/security/plugin.py
CKAN has special response middleware that overrides
the content/body of the response for certain status
codes. However, it does not apply on routes under
the /api paths so we can make sure the response type
can be consistently json regardless of the status
code.
> Use /api path for ajax login call

- README.md
- ckanext/security/controllers.py
- ckanext/security/fanstatic/login_ajax.js
- ckanext/security/templates/user/snippets/login_form.html
- setup.py
This little config addon allows you to specify a help page with useful information about how to set up and manage 2fa logins. This could be a useful place to detail your 2fa reset process if a user has lost their auth device.
> DATA-860 2fa reset link

- README.md
- ckanext/security/authenticator.py
- ckanext/security/logic/action.py
- ckanext/security/logic/auth.py
- ckanext/security/plugin.py
- setup.py
- Add actions to query and reset throttle controls (sysadmin-only)
- Reset user lockout when their record is updated, e.g. on a successful password reset
- fix pyotp dependency for Python 2
> API for throttle control, reset user throttle on update

- ckanext/security/authenticator.py
- ckanext/security/logic/action.py
- ckanext/security/logic/auth.py
- ckanext/security/plugin/__init__.py
In working through the tests for our main repo I found that they where slowed down a lot by having to use the ckan cli to reset TOTP codes. To attempt to speed this up I have added a reset action for the TOTP codes. I think there was a suggestion somewhere to add this functionality but I can't recall where it was.
> Add an action to allow the resetting of users totp.

- ckanext/security/mailer.py
The render_jinja2() call in _build_footer_content() was failing on CKAN 2.9.5, which causes the notify_lockout functionality to fail.
An is_flask_request() conditional was added to fix the problem.
> Added "if is_flask_request" inside _build_footer_content() to fix notify_lockout() functionality in CKAN 2.9.5

- ckanext/security/authenticator.py
Base CKAN authenticate function used to return a
username, but was changed in 2.9.6 to return a
comma separated "user_id,1"
We should not have been assuming the return value
of the super.authenticate, we now return the super value after doing our throttle and totp checks.
> Fix auth implementation to return super result

- requirements.txt
I can't see anywhere in the code that the `zope.interface` library is used and due to the version being inconsistent to what's used by CKAN I have removed it.
> Remove zope.interface requirement as it doesn't appear to be used.

- ckanext/security/resource_upload_validator.py
This issue was originally reported in https://github.com/data-govt-nz/ckanext-security/issues/42
We ran into this after altering the base docker image that our CKAN installation was hosted in. It appears that some versions of debian set the mime.config files in such a way that text/plain does not resolve to a .bat extension, and others do.
This change means that plain text files will no longer be blocked based on guessing the possible extension and matching against the blacklist.
If you want to explicitly block plaintext files, you can add 'text/plain' to the block list.
> Don't get extensions for plaintext files

- ckanext/security/plugin/__init__.py
These validation rules prevent creation of datastore-only resources or resources that don't (yet) have a link to a file. I can't think of a reason that creating resources with no url or file should be prevented by ckanext-security.
> resources with no url/file are safe

- README.md
- ckanext/security/authenticator.py
- ckanext/security/helpers.py
- ckanext/security/plugin/__init__.py
- ckanext/security/templates/user/edit_user_form.html
- ckanext/security/templates/user/snippets/login_form.html
In response to https://github.com/data-govt-nz/ckanext-security/issues/40. 
Add option to disable totp using `ckanext.security.enable_totp = false` in configurations. The default value for the flag is `True` if the option is not set in configurations.
> Disable totp authentication, if needed

- ckanext/security/authenticator.py
- ckanext/security/plugin/flask_plugin.py
The MFA implementation leverages an ajax form submit to add the two step user/pass then MFA code form structure into CKAN.
Once that ajax response from the /api/login succeeds the login form does a normal form POST submit to the overridden IAuthenticator implementation, which rechecks the user/pass and MFA, and returns the result of the default CKAN authenticator if everything succeeds.
We were returning "None" in the case that MFA fails, however the IAuthenticator implementation in CKAN core falls back to user/pass auth if the plugin returns None, so this meant that the form was able to be submitted with no MFA and as long as the user/pass was correct the user could still log in.
This required malicious intent, either through man-in-the-middle to alter the response of the /api/login …
> Abort if user/pass auth success but no MFA
